FROM node:18

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
COPY knexfile.cjs ./
COPY .env.docker ./
COPY jest.config.js ./

RUN apt-get update && apt-get install -y netcat-openbsd

RUN npm ci

COPY src ./src
COPY db ./db
COPY tests ./tests

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["npm", "run", "test:integration"]